#!/bin/bash

phpize
aclocal
libtoolize --force
autoheader
autoconf
./configure --enable-murmurhash3
make
sudo make install
sudo cp 06_murmurhash3.ini /etc/php/apache2-php5.3/ext/murmurhash3.ini
sudo ln -sf /etc/php/apache2-php5.3/ext/murmurhash3.ini /etc/php/apache2-php5.3/ext-active/murmurhash3.ini
sudo cp 06_murmurhash3.ini /etc/php/cli-php5.3/ext/murmurhash3.ini
sudo ln -sf /etc/php/cli-php5.3/ext/murmurhash3.ini /etc/php/cli-php5.3/ext-active/murmurhash3.ini

